image: bitcoincashnode/buildenv:debian

stages:
    - build
    - build_tests
    - test

variables:
    # Don't allow tests to hang
    TRAVIS: 1

default:
    before_script:
        - "mkdir -p ccache"
        - "export CCACHE_BASEDIR=${PWD}"
        - "export CCACHE_DIR=${PWD}/ccache"


cache:
    paths:
        - "ccache/"

build-debian-stable:
    stage: build
    script:
        - "mkdir build"
        - "cd build"
        - "cmake -GNinja .."

        - "ninja"

        # Show ccache stats
        - "ccache -s"
    artifacts:
        paths:
            - build
            - test

build-tests-debian-stable:
    stage: build_tests
    script:
        - "(cd build; ninja test_bitcoin)"
        - "(cd build; ninja check-bitcoin-qt \
              check-bitcoin-seeder \
              check-bitcoin-util \
              check-devtools \
              check-leveldb \
              check-rpcauth \
              check-secp256k1 \
              check-univalue)"

        # Show ccache stats
        - "ccache -s"
    artifacts:
        paths:
            - build
            - test
    dependencies:
        - build-debian-stable

test_bitcoin:
    stage: test
    cache: {}
    script:
        - "./build/src/test/test_bitcoin"
    dependencies:
        - build-tests-debian-stable

test_bitcoin_post_phonon:
    stage: test
    cache: {}
    script:
        - "./build/src/test/test_bitcoin -- -phononactivationtime=1575158400"
    dependencies:
        - build-tests-debian-stable

test_functional:
    stage: test

    script:
        - "(cd build; ninja check-functional)"
    dependencies:
        - build-tests-debian-stable

test_functional_post_phonon:
    stage: test
    script:
        - "(cd build; ninja check-functional-upgrade-activated)"
    dependencies:
        - build-tests-debian-stable

