site_name: Bitcoin Cash Node documentation
site_url: https://docs.bitcoincashnode.org
site_description: Documentation for the Bitcoin Cash Node project
site_author: The Bitcoin Developers

repo_url: https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node
edit_uri: ""

docs_dir: doc

theme:
    name: material
    logo: images/logo.svg

extra_css:
  - stylesheets/custom.css

plugins:
    - exclude:
        glob:
            release-notes.md

nav:
    - Home: README.md
    - API:
        - Command-line interfaces:
            - bitcoind: cli/bitcoind.md
            - bitcoin-qt: cli/bitcoin-qt.md
            - bitcoin-cli: cli/bitcoin-cli.md
            - bitcoin-tx: cli/bitcoin-tx.md
            - bitcoin-seeder: cli/bitcoin-seeder.md
        - JSON-RPC interface:
            - JSON-RPC commands list: json-rpc/README.md
            - Blockchain:
                - finalizeblock: json-rpc/finalizeblock.md
                - getbestblockhash: json-rpc/getbestblockhash.md
                - getblock: json-rpc/getblock.md
                - getblockchaininfo: json-rpc/getblockchaininfo.md
                - getblockcount: json-rpc/getblockcount.md
                - getblockhash: json-rpc/getblockhash.md
                - getblockheader: json-rpc/getblockheader.md
                - getblockstats: json-rpc/getblockstats.md
                - getchaintips: json-rpc/getchaintips.md
                - getchaintxstats: json-rpc/getchaintxstats.md
                - getdifficulty: json-rpc/getdifficulty.md
                - getfinalizedblockhash: json-rpc/getfinalizedblockhash.md
                - getmempoolancestors: json-rpc/getmempoolancestors.md
                - getmempooldescendants: json-rpc/getmempooldescendants.md
                - getmempoolentry: json-rpc/getmempoolentry.md
                - getmempoolinfo: json-rpc/getmempoolinfo.md
                - getrawmempool: json-rpc/getrawmempool.md
                - gettxout: json-rpc/gettxout.md
                - gettxoutproof: json-rpc/gettxoutproof.md
                - gettxoutsetinfo: json-rpc/gettxoutsetinfo.md
                - invalidateblock: json-rpc/invalidateblock.md
                - parkblock: json-rpc/parkblock.md
                - preciousblock: json-rpc/preciousblock.md
                - pruneblockchain: json-rpc/pruneblockchain.md
                - reconsiderblock: json-rpc/reconsiderblock.md
                - savemempool: json-rpc/savemempool.md
                - scantxoutset: json-rpc/scantxoutset.md
                - unparkblock: json-rpc/unparkblock.md
                - verifychain: json-rpc/verifychain.md
                - verifytxoutproof: json-rpc/verifytxoutproof.md
            - Control:
                - getmemoryinfo: json-rpc/getmemoryinfo.md
                - getrpcinfo: json-rpc/getrpcinfo.md
                - help: json-rpc/help.md
                - logging: json-rpc/logging.md
                - stop: json-rpc/stop.md
                - uptime: json-rpc/uptime.md
            - Generating:
                - generate: json-rpc/generate.md
                - generatetoaddress: json-rpc/generatetoaddress.md
            - Mining:
                - getblocktemplate: json-rpc/getblocktemplate.md
                - getblocktemplatelight: json-rpc/getblocktemplatelight.md
                - getmininginfo: json-rpc/getmininginfo.md
                - getnetworkhashps: json-rpc/getnetworkhashps.md
                - prioritisetransaction: json-rpc/prioritisetransaction.md
                - submitblock: json-rpc/submitblock.md
                - submitblocklight: json-rpc/submitblocklight.md
                - submitheader: json-rpc/submitheader.md
            - Network:
                - addnode: json-rpc/addnode.md
                - clearbanned: json-rpc/clearbanned.md
                - disconnectnode: json-rpc/disconnectnode.md
                - getaddednodeinfo: json-rpc/getaddednodeinfo.md
                - getconnectioncount: json-rpc/getconnectioncount.md
                - getexcessiveblock: json-rpc/getexcessiveblock.md
                - getnettotals: json-rpc/getnettotals.md
                - getnetworkinfo: json-rpc/getnetworkinfo.md
                - getnodeaddresses: json-rpc/getnodeaddresses.md
                - getpeerinfo: json-rpc/getpeerinfo.md
                - listbanned: json-rpc/listbanned.md
                - ping: json-rpc/ping.md
                - setban: json-rpc/setban.md
                - setexcessiveblock: json-rpc/setexcessiveblock.md
                - setnetworkactive: json-rpc/setnetworkactive.md
            - Rawtransactions:
                - combinepsbt: json-rpc/combinepsbt.md
                - combinerawtransaction: json-rpc/combinerawtransaction.md
                - converttopsbt: json-rpc/converttopsbt.md
                - createpsbt: json-rpc/createpsbt.md
                - createrawtransaction: json-rpc/createrawtransaction.md
                - decodepsbt: json-rpc/decodepsbt.md
                - decoderawtransaction: json-rpc/decoderawtransaction.md
                - decodescript: json-rpc/decodescript.md
                - finalizepsbt: json-rpc/finalizepsbt.md
                - fundrawtransaction: json-rpc/fundrawtransaction.md
                - getrawtransaction: json-rpc/getrawtransaction.md
                - sendrawtransaction: json-rpc/sendrawtransaction.md
                - signrawtransactionwithkey: json-rpc/signrawtransactionwithkey.md
                - testmempoolaccept: json-rpc/testmempoolaccept.md
            - Util:
                - createmultisig: json-rpc/createmultisig.md
                - estimatefee: json-rpc/estimatefee.md
                - signmessagewithprivkey: json-rpc/signmessagewithprivkey.md
                - validateaddress: json-rpc/validateaddress.md
                - verifymessage: json-rpc/verifymessage.md
            - Wallet:
                - abandontransaction: json-rpc/abandontransaction.md
                - abortrescan: json-rpc/abortrescan.md
                - addmultisigaddress: json-rpc/addmultisigaddress.md
                - backupwallet: json-rpc/backupwallet.md
                - createwallet: json-rpc/createwallet.md
                - dumpprivkey: json-rpc/dumpprivkey.md
                - dumpwallet: json-rpc/dumpwallet.md
                - encryptwallet: json-rpc/encryptwallet.md
                - getaddressesbylabel: json-rpc/getaddressesbylabel.md
                - getaddressinfo: json-rpc/getaddressinfo.md
                - getbalance: json-rpc/getbalance.md
                - getnewaddress: json-rpc/getnewaddress.md
                - getrawchangeaddress: json-rpc/getrawchangeaddress.md
                - getreceivedbyaddress: json-rpc/getreceivedbyaddress.md
                - getreceivedbylabel: json-rpc/getreceivedbylabel.md
                - gettransaction: json-rpc/gettransaction.md
                - getunconfirmedbalance: json-rpc/getunconfirmedbalance.md
                - getwalletinfo: json-rpc/getwalletinfo.md
                - importaddress: json-rpc/importaddress.md
                - importmulti: json-rpc/importmulti.md
                - importprivkey: json-rpc/importprivkey.md
                - importprunedfunds: json-rpc/importprunedfunds.md
                - importpubkey: json-rpc/importpubkey.md
                - importwallet: json-rpc/importwallet.md
                - keypoolrefill: json-rpc/keypoolrefill.md
                - listaddressgroupings: json-rpc/listaddressgroupings.md
                - listlabels: json-rpc/listlabels.md
                - listlockunspent: json-rpc/listlockunspent.md
                - listreceivedbyaddress: json-rpc/listreceivedbyaddress.md
                - listreceivedbylabel: json-rpc/listreceivedbylabel.md
                - listsinceblock: json-rpc/listsinceblock.md
                - listtransactions: json-rpc/listtransactions.md
                - listunspent: json-rpc/listunspent.md
                - listwalletdir: json-rpc/listwalletdir.md
                - listwallets: json-rpc/listwallets.md
                - loadwallet: json-rpc/loadwallet.md
                - lockunspent: json-rpc/lockunspent.md
                - removeprunedfunds: json-rpc/removeprunedfunds.md
                - rescanblockchain: json-rpc/rescanblockchain.md
                - sendmany: json-rpc/sendmany.md
                - sendtoaddress: json-rpc/sendtoaddress.md
                - sethdseed: json-rpc/sethdseed.md
                - setlabel: json-rpc/setlabel.md
                - settxfee: json-rpc/settxfee.md
                - signmessage: json-rpc/signmessage.md
                - signrawtransactionwithwallet: json-rpc/signrawtransactionwithwallet.md
                - unloadwallet: json-rpc/unloadwallet.md
                - walletcreatefundedpsbt: json-rpc/walletcreatefundedpsbt.md
                - walletprocesspsbt: json-rpc/walletprocesspsbt.md
            - Zmq:
                - getzmqnotifications: json-rpc/getzmqnotifications.md
        - REST-interface.md
        - Output descriptors: descriptors.md
        - getblocktemplatelight: getblocktemplatelight.md
        - ZeroMQ: zmq.md
    - Release notes:
        - release-notes/release-notes-0.21.1.md
        - release-notes/release-notes-0.21.0.md
        - Bitcoin ABC 0.14.1-0.20:
            - release-notes/release-notes-0.20.12.md
            - release-notes/release-notes-0.20.11.md
            - release-notes/release-notes-0.20.10.md
            - release-notes/release-notes-0.20.9.md
            - release-notes/release-notes-0.20.8.md
            - release-notes/release-notes-0.20.7.md
            - release-notes/release-notes-0.20.6.md
            - release-notes/release-notes-0.20.5.md
            - release-notes/release-notes-0.20.4.md
            - release-notes/release-notes-0.20.3.md
            - release-notes/release-notes-0.20.2.md
            - release-notes/release-notes-0.20.1.md
            - release-notes/release-notes-0.20.0.md
            - release-notes/release-notes-0.19.12.md
            - release-notes/release-notes-0.19.11.md
            - release-notes/release-notes-0.19.10.md
            - release-notes/release-notes-0.19.9.md
            - release-notes/release-notes-0.19.8.md
            - release-notes/release-notes-0.19.7.md
            - release-notes/release-notes-0.19.6.md
            - release-notes/release-notes-0.19.5.md
            - release-notes/release-notes-0.19.4.md
            - release-notes/release-notes-0.19.3.md
            - release-notes/release-notes-0.19.2.md
            - release-notes/release-notes-0.19.1.md
            - release-notes/release-notes-0.19.0.md
            - release-notes/release-notes-0.18.8.md
            - release-notes/release-notes-0.18.7.md
            - release-notes/release-notes-0.18.6.md
            - release-notes/release-notes-0.18.5.md
            - release-notes/release-notes-0.18.4.md
            - release-notes/release-notes-0.18.3.md
            - release-notes/release-notes-0.18.2.md
            - release-notes/release-notes-0.18.1.md
            - release-notes/release-notes-0.18.0.md
            - release-notes/release-notes-0.17.2.md
            - release-notes/release-notes-0.17.1.md
            - release-notes/release-notes-0.17.0.md
            - release-notes/release-notes-0.16.2.md
            - release-notes/release-notes-0.16.1.md
            - release-notes/release-notes-0.16.0.md
            - release-notes/release-notes-0.15.1.md
            - release-notes/release-notes-0.15.0.md
            - release-notes/release-notes-0.14.6.md
            - release-notes/release-notes-0.14.5.md
            - release-notes/release-notes-0.14.4.md
            - release-notes/release-notes-0.14.3.md
            - release-notes/release-notes-0.14.2.md
            - release-notes/release-notes-0.14.1.md
        - Bitcoin Core 0.9-0.14.0:
            - release-notes/release-notes-0.14.0.md
            - release-notes/release-notes-0.13.2.md
            - release-notes/release-notes-0.13.1.md
            - release-notes/release-notes-0.13.0.md
            - release-notes/release-notes-0.12.1.md
            - release-notes/release-notes-0.12.0.md
            - release-notes/release-notes-0.11.2.md
            - release-notes/release-notes-0.11.1.md
            - release-notes/release-notes-0.11.0.md
            - release-notes/release-notes-0.10.4.md
            - release-notes/release-notes-0.10.3.md
            - release-notes/release-notes-0.10.2.md
            - release-notes/release-notes-0.10.1.md
            - release-notes/release-notes-0.10.0.md
            - release-notes/release-notes-0.9.5.md
            - release-notes/release-notes-0.9.4.md
            - release-notes/release-notes-0.9.3.md
            - release-notes/release-notes-0.9.2.1.md
            - release-notes/release-notes-0.9.2.md
            - release-notes/release-notes-0.9.1.md
            - release-notes/release-notes-0.9.0.md
        - Bitcoin-Qt 0.5-0.8:
            - release-notes/release-notes-0.8.6.md
            - release-notes/release-notes-0.8.5.md
            - release-notes/release-notes-0.8.4.md
            - release-notes/release-notes-0.8.3.md
            - release-notes/release-notes-0.8.2.md
            - release-notes/release-notes-0.8.1.md
            - release-notes/release-notes-0.8.0.md
            - release-notes/release-notes-0.7.2.md
            - release-notes/release-notes-0.7.1.md
            - release-notes/release-notes-0.7.0.md
            - release-notes/release-notes-0.6.3.md
            - release-notes/release-notes-0.6.2.md
            - release-notes/release-notes-0.6.1.md
            - release-notes/release-notes-0.6.0.md
            - release-notes/release-notes-0.5.5.md
            - release-notes/release-notes-0.5.4.md
            - release-notes/release-notes-0.5.3.md
            - release-notes/release-notes-0.5.2.md
            - release-notes/release-notes-0.5.1.md
            - release-notes/release-notes-0.5.0.md
        - Bitcoin 0.1-0.4:
            - release-notes/release-notes-0.4.6.md
            - release-notes/release-notes-0.4.5.md
            - release-notes/release-notes-0.4.4.md
            - release-notes/release-notes-0.4.3.md
            - release-notes/release-notes-0.4.2.md
            - release-notes/release-notes-0.4.1.md
            - release-notes/release-notes-0.4.0.md
            - release-notes/release-notes-0.3.24.md
            - release-notes/release-notes-0.3.23.md
            - release-notes/release-notes-0.3.22.md
            - release-notes/release-notes-0.3.21.md
            - release-notes/release-notes-0.3.20.2.md
            - release-notes/release-notes-0.3.20.1.md
            - release-notes/release-notes-0.3.20.md
            - release-notes/release-notes-0.3.19.md
            - release-notes/release-notes-0.3.18.md
            - release-notes/release-notes-0.3.17.md
            - release-notes/release-notes-0.3.16.md
            - release-notes/release-notes-0.3.15.md
            - release-notes/release-notes-0.3.14.md
            - release-notes/release-notes-0.3.13.md
            - release-notes/release-notes-0.3.12.md
    - Deployment:
        - build-freebsd.md
        - build-osx.md
        - build-unix.md
        - build-windows.md
        - dependencies.md
        - dnsseed-policy.md
        - files.md
        - init.md
        - publishing-documentation.md
        - Packaging:
            - README_osx.md
            - build-unix-arch.md
            - build-unix-deb.md
            - build-unix-rpm.md
        - Gitian:
            - gitian-building.md
            - gitian-signing.md
            - gitian-building/gitian-building-create-vm-debian.md
            - gitian-building/gitian-building-manual.md
            - gitian-building/gitian-building-setup-gitian-debian.md
            - gitian-building/gitian-building-vagrant.md
    - Development:
        - backporting.md
        - bchn-gitlab-usage-rules-and-guidelines.md
        - benchmarking.md
        - developer-notes.md
        - functional-tests.md
        - fuzzing.md
        - ninja_targets.md
        - rapidcheck.md
        - release-process.md
        - shared-libraries.md
        - translation_process.md
        - translation_strings_policy.md
        - unit-tests.md
    - Protocol:
        - abc/replay-protected-sighash.md
        - abc/uahf-technical-spec.md
        - abc/uahf-test-plan.md
        - bips.md
        - xversionmessage.md
    - Miscellaneous:
        - assets-attribution.md
        - reduce-traffic.md
        - tor.md

